### ISSUE TITLE
Package Missing in osx-64 Channels

### ISSUE THREAD

**Issue by timzhang642** [daavoo/pyntcloud#107] opened 2017-07-01 16:55 UTC
Hi,

I am using Anaconda on an OSX-64 machine. While I was trying to create the pyntcloud environment with the enviroment.yml, it prompted the following error: 

```
NoPackagesFoundError: Package missing in current osx-64 channels: 
  - gst-plugins-base 1.8.0 0
```
Do you know how to solve this?

Thanks!

**Comment by daavoo** [comment] 2017-07-01 18:54
Holly molly. I have no idea where that dependency comes from :astonished: and I have to admit that I didn't tested the enviroment in OSX.

Can you try to install the dependencies listed in the requirements section of https://github.com/daavoo/pyntcloud and see what is the package that generates the conflict in OSX??

**Comment by daavoo** [comment] 2017-07-04 17:08
Ok. So I found the problem. The conda-forge matplotlib package comes with gstreamer as dependency for some reason. In addition, the current enviroment.yml has some unnecessary dependencies.

I'm going to update the installation documentation to make things clearer and add new enviroment and requirements file.

**Comment by daavoo** [comment] 2017-07-04 21:05
I tested the new enviroment files #110 on OSX and everithing went fine.

@timzhang642  Can you confirm this?

**Comment by timzhang642** [comment] 2017-07-05 00:00
I tried using the new env.yml and it installed fine until reaching "cycler==0.10.0". Below is the error message returned:

`Collecting cycler==0.10.0`

 ` Downloading cycler-0.10.0-py2.py3-none-any.whl`
`dyld: lazy symbol binding failed: Symbol not found: _fdopendir$INODE64
  Referenced from: /Users/yuxuanzhang/anaconda/envs/pyntcloud/lib/libpython3.6m.dylib
  Expected in: /usr/lib/libSystem.B.dylib`

`dyld: Symbol not found: _fdopendir$INODE64
  Referenced from: /Users/yuxuanzhang/anaconda/envs/pyntcloud/lib/libpython3.6m.dylib
  Expected in: /usr/lib/libSystem.B.dylib`

`CondaValueError: pip returned an error.`

**Comment by daavoo** [comment] 2017-07-05 06:23
:(

What  OSX are you using??

Are you running it in virtualbox or something like that??

Seems to be a problem with matplotlib+OSX. 

I will upload a new env file for you to try.

**Comment by timzhang642** [comment] 2017-07-05 15:17
`ProductName:	Mac OS X`
`ProductVersion:	10.9.2`
`BuildVersion:	13C64`
`Python 2.7.13 :: Anaconda custom (x86_64)`

I'm running it under the current OS, no virtualbox involved, for now. Your help is much appreciated!

**Comment by daavoo** [comment] 2017-07-05 15:43
Can you try with this enviroment file:

https://gist.github.com/daavoo/4a4750aadea7554c65d49d02c410eac2

It tries to install matplotlib from anaconda defaults channel.

**Comment by timzhang642** [comment] 2017-07-05 16:41
This is time it returns this:
`Collecting laspy==1.5.0
  Using cached laspy-1.5.0-py3-none-any.whl`
`dyld: lazy symbol binding failed: Symbol not found: _fdopendir$INODE64
  Referenced from: /Users/yuxuanzhang/anaconda/envs/pyntcloud/lib/libpython3.6m.dylib
  Expected in: /usr/lib/libSystem.B.dylib`

`dyld: Symbol not found: _fdopendir$INODE64
  Referenced from: /Users/yuxuanzhang/anaconda/envs/pyntcloud/lib/libpython3.6m.dylib
  Expected in: /usr/lib/libSystem.B.dylib`

I guess it is the same problem..

**Comment by timzhang642** [comment] 2017-07-05 16:42
matplotlib-2.0 was installed successfully though

**Comment by daavoo** [comment] 2017-07-05 17:09
Getting a different error is always a nice thing xD

This time the problem is laspy.

I'll look into this.

**Comment by themmes** [comment] 2017-12-08 13:23
I have not much experience in this, bit maybe you can avoid the laspy dependency and its difficult laszip dependencies by using this https://github.com/verma/plasio/blob/master/js/laslaz.js Javascript implementation? Since you're making a nice combination of python and js already?

**Comment by daavoo** [comment] 2017-12-08 18:07
@timzhang642 In #140 I modified the installation process to accept optional dependencies. Laspy and matplotlib are no longer mandatory dependencies. The new installation process will be documented as soon as possible but I'm closing this as I understand that the packages causing the problem are no longer needed for installing pyntcloud. If you DO want to use the features that require laspy or matplotlib please feel free to reopen the issue or open a new one.

**Closed by daavoo** 2017-12-08 18:07 UTC
