### ISSUE TITLE
Loading obj file doesn't work for objects which do not only consist of triangles

### ISSUE THREAD

**Issue by hildensia** [daavoo/pyntcloud#168] opened 2018-05-08 08:16 UTC
When I attempt to load a obj file, which has e.g. rectangles as facet pyntcloud crashes with an `AssertionError` within pandas:

    ---------------------------------------------------------------------------
    AssertionError                            Traceback (most recent call last)
    <ipython-input-36-170af64711ff> in <module>()
    ----> 1 obj.read_obj("/Users/johannes/test.obj")
    
    ~/anaconda3/envs/suction/lib/python3.6/site-packages/pyntcloud/io/obj.py in read_obj(filename)
         50     f = [re.split(r'\D+', x) for x in f]
         51 
    ---> 52     mesh = pd.DataFrame(f, dtype='i4', columns=mesh_columns)
         53     # start index at 0
         54     mesh -= 1
    
    ~/anaconda3/envs/suction/lib/python3.6/site-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
        367                     if is_named_tuple(data[0]) and columns is None:
        368                         columns = data[0]._fields
    --> 369                     arrays, columns = _to_arrays(data, columns, dtype=dtype)
        370                     columns = _ensure_index(columns)
        371 
    
    ~/anaconda3/envs/suction/lib/python3.6/site-packages/pandas/core/frame.py in _to_arrays(data,     columns, coerce_float, dtype)
       6282     if isinstance(data[0], (list, tuple)):
       6283         return _list_to_arrays(data, columns, coerce_float=coerce_float,
    -> 6284                                dtype=dtype)
       6285     elif isinstance(data[0], collections.Mapping):
       6286         return _list_of_dict_to_arrays(data, columns,

    ~/anaconda3/envs/suction/lib/python3.6/site-packages/pandas/core/frame.py in _list_to_arrays(data, columns, coerce_float, dtype)
       6361         content = list(lib.to_object_array(data).T)
       6362     return _convert_object_array(content, columns, dtype=dtype,
    -> 6363                                  coerce_float=coerce_float)
       6364 
       6365 

    ~/anaconda3/envs/suction/lib/python3.6/site-packages/pandas/core/frame.py in _convert_object_array(content, columns, coerce_float, dtype)
       6418             # caller's responsibility to check for this...
       6419             raise AssertionError('%d columns passed, passed data had %s '
    -> 6420                                  'columns' % (len(columns), len(content)))
       6421 
       6422     # provide soft conversion of object dtypes
    
    AssertionError: 9 columns passed, passed data had 12 columns

**Comment by daavoo** [comment] 2018-05-09 05:01
Hola! 
Thanks for pointing this out! 

I'm aware that the current .obj parser does not cover the entire file format capabilities.

Could you share the file that is causing the error??

**Comment by hildensia** [comment] 2018-05-09 08:41
Unfortunately, no. But I can see, if I can generate a simple example generating the same defect.

**Comment by hildensia** [comment] 2018-05-09 08:47
The following files create the same error:

test.obj:
    
    # Blender v2.79 (sub 0) OBJ File: ''
    # www.blender.org
    mtllib test.mtl
    o Cube
    v 1.000000 -1.000000 -1.000000
    v 1.000000 -1.000000 1.000000
    v -1.000000 -1.000000 1.000000
    v -1.000000 -1.000000 -1.000000
    v 1.000000 1.000000 -0.999999
    v 0.999999 1.000000 1.000001
    v -1.000000 1.000000 1.000000
    v -1.000000 1.000000 -1.000000
    vn 0.0000 -1.0000 0.0000
    vn 0.0000 1.0000 0.0000
    vn 1.0000 0.0000 0.0000
    vn -0.0000 -0.0000 1.0000
    vn -1.0000 -0.0000 -0.0000
    vn 0.0000 0.0000 -1.0000
    usemtl Material
    s off
    f 1//1 2//1 3//1 4//1
    f 5//2 8//2 7//2 6//2
    f 1//3 5//3 6//3 2//3
    f 2//4 6//4 7//4 3//4
    f 3//5 7//5 8//5 4//5
    f 5//6 1//6 4//6 8//6

test.tml (I don't know if this is even needed):

    # Blender MTL File: 'None'
    # Material Count: 1
    
    newmtl Material
    Ns 96.078431
    Ka 1.000000 1.000000 1.000000
    Kd 0.640000 0.640000 0.640000
    Ks 0.500000 0.500000 0.500000
    Ke 0.000000 0.000000 0.000000
    Ni 1.000000
    d 1.000000
    illum 2

**Comment by hildensia** [comment] 2018-05-09 08:48
The problem lies within the facet lines (`f 1//1 2//1 3//1 4//1` etc.) - pyntcloud assumes there will always be three vertices.

**Comment by daavoo** [comment] 2018-07-29 21:16
After #209 This should be fixed. A utility for converting quadrilateral faces to triangular has also been added. In summary, the following code should work as intended:

```python
from pyntcloud import PyntCloud
from pyntcloud.utils.mesh import quadrilateral_to_triangular
cloud = PyntCloud.from_file("test.obj")
cloud.mesh = quadrilateral_to_triangular(cloud.mesh)
```

**Closed** 2018-07-29 21:16 UTC
Labels: Bug, Debate

**Comment by MaveriQ** [comment] 2018-11-28 18:23
I am having similar error. The thing is that the error occurs when we are reading the file (in PyntCloud.from_file('..') line) so it doesn't reach the line where quadrilateral faces are converted.

**Comment by walus90** [comment] 2018-12-08 10:43
I have the same issue. @daavoo your workaround does not work as pointed in previous comment. Could you provide another workaround please?
